spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    #driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
logging:
  level:
    org:
      hibernate:
        SQL:
          DEBUG
        TYPE:
          TRACE
  com:
    example:
      weblab:
        level: INFO


